// tdd-cover: e2e packages/hook-runner/src/enforcement/syntax-inspection.test.ts
// Generated by scripts/build-runtime.mjs. Do not edit.
export const SYNTAX_WORKER_IDENTITY = {"sha256":"12e6a141d5bda6486f285da9af96d09c638ceb26a321f1362a1df064b8eefea3","bytes":3588399};
