// `voidcorp-harness init` — initialize the current project.
//
// Actions:
//  1. Create `.voidcorp/config.json` with sensible defaults (unless already exists)
//  2. Create `CLAUDE.md` + `AGENTS.md` (sister docs) at repo root, composed from
//     core modules + any active packs
//  3. Wire up the sync hook (.husky / lefthook.yml — detect existing convention)
//
// Optional: --pack <name> to activate a stack pack at init time.

import { existsSync } from 'node:fs';
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

interface InitOptions {
  readonly packs: readonly string[];
  readonly force: boolean;
}

function parseArgs(args: readonly string[]): InitOptions {
  const packs: string[] = [];
  let force = false;
  for (let i = 0; i < args.length; i += 1) {
    const a = args[i] ?? '';
    if (a === '--pack' && i + 1 < args.length) {
      const next = args[i + 1];
      if (next !== undefined) packs.push(next);
      i += 1;
    } else if (a === '--force') {
      force = true;
    }
  }
  return { packs, force };
}

const DEFAULT_CONFIG = {
  core: '^0.1.0',
  packs: {} as Record<string, string>,
  stack: {
    packageManager: 'bun',
    testRunner: 'vitest',
    e2eRunner: 'playwright',
  },
  paths: {
    business: 'apps/*/src/**',
    tests: 'apps/*/src/**/*.test.{ts,tsx}',
    spikes: 'apps/*/scripts/spike-*',
    serverActions: 'apps/*/src/app/(api|actions)/**',
    contracts: 'apps/*/src/lib/contracts/**',
    e2e: 'apps/*/tests/e2e/**',
  },
  commands: {
    typecheck: 'bunx tsc --noEmit',
    testUnit: 'bunx vitest run',
    testE2e: 'bunx playwright test',
    mutation: 'bunx stryker run',
  },
  modes: {
    tdd: 'auto' as const,
    codeReview: 'auto' as const,
  },
} as const;

export async function init(args: readonly string[]): Promise<void> {
  const opts = parseArgs(args);
  const projectRoot = process.cwd();
  const voidcorpDir = join(projectRoot, '.voidcorp');
  const configPath = join(voidcorpDir, 'config.json');

  console.log(`voidcorp-harness init`);
  console.log(`  project: ${projectRoot}`);

  // 1. Config
  if (existsSync(configPath) && !opts.force) {
    console.log(`  config : .voidcorp/config.json already exists (use --force to overwrite)`);
  } else {
    await mkdir(voidcorpDir, { recursive: true });
    const config = structuredClone(DEFAULT_CONFIG) as Record<string, unknown> & {
      packs: Record<string, string>;
    };
    for (const pack of opts.packs) {
      config.packs[`@voidcorp/${pack}`] = '^0.1.0';
    }
    await writeFile(configPath, `${JSON.stringify(config, null, 2)}\n`);
    console.log(`  config : .voidcorp/config.json written`);
  }

  // 2. CLAUDE.md + AGENTS.md (placeholder for now — composition logic in Phase B+)
  for (const name of ['CLAUDE.md', 'AGENTS.md']) {
    const target = join(projectRoot, name);
    if (existsSync(target) && !opts.force) {
      console.log(`  ${name.padEnd(7)}: already exists (use --force to overwrite)`);
      continue;
    }
    await writeFile(
      target,
      [
        `# ${name === 'CLAUDE.md' ? 'CLAUDE.md' : 'AGENTS.md'}`,
        '',
        `> Sister doc to ${name === 'CLAUDE.md' ? 'AGENTS.md' : 'CLAUDE.md'}.`,
        '> Maintained in sync — modifying one requires reflecting in the other.',
        '',
        `Generated by voidcorp-harness init.`,
        '',
        '## Active harness components',
        '',
        `- core: ${DEFAULT_CONFIG.core}`,
        ...opts.packs.map((p) => `- pack: @voidcorp/${p}`),
        '',
        '## How this project loads the harness',
        '',
        `See \`.voidcorp/config.json\` for paths, commands, and modes.`,
        `Run \`npx @voidcorp/harness doctor\` to verify the install.`,
        '',
      ].join('\n'),
    );
    console.log(`  ${name.padEnd(7)}: written`);
  }

  console.log(`done.`);
  console.log(``);
  console.log(`Next steps:`);
  console.log(`  1. Review .voidcorp/config.json — adjust paths/commands for your stack`);
  console.log(`  2. Run 'npx @voidcorp/harness doctor' to verify`);
  console.log(`  3. Commit the .voidcorp/, CLAUDE.md, AGENTS.md files`);
}
