#!/usr/bin/env bash
# protect-sensitive-files — PreToolUse hook. Reads Claude Code JSON from stdin.
# Blocks edits to files that should never be hand-edited by the agent: private
# keys, credential files, lockfiles, and anything under .git/. This is the
# safety floor for unattended / autonomous runs (blast-radius control).
#
# Override (a legitimate, deliberate edit): export VOID_HARNESS_ALLOW_SECRET_EDIT=1
# for the single run. The autonomous-backlog-loop deliberately leaves it unset.
#
# Exit codes: 0 allow, 2 block.

set -euo pipefail

INPUT=$(cat)
TOOL=$(printf "%s" "$INPUT" | jq -r '.tool_name // empty')
FILE=$(printf "%s" "$INPUT" | jq -r '.tool_input.file_path // empty')

case "$TOOL" in Edit|Write) ;; *) exit 0 ;; esac
[[ -z "$FILE" ]] && exit 0
[[ "${VOID_HARNESS_ALLOW_SECRET_EDIT:-}" == "1" ]] && exit 0

base=$(basename "$FILE")

# .env files are protected EXCEPT the committed example templates.
if [[ "$base" =~ ^\.env(\..+)?$ ]] && [[ ! "$base" =~ \.(example|sample|template|dist)$ ]]; then
  REASON="environment file with secrets"
fi

# Private keys / certificates / keystores.
if [[ "$base" =~ \.(pem|key|p12|pfx|keystore|jks|asc)$ || "$base" =~ ^id_(rsa|ed25519|ecdsa|dsa)$ ]]; then
  REASON="private key / certificate"
fi

# Credential-bearing filenames.
if [[ "$base" =~ (secret|credential|\.npmrc$|\.netrc$|\.pgpass$) ]]; then
  REASON="credential file"
fi

# Lockfiles must be regenerated by the package manager, never hand-edited.
case "$base" in
  package-lock.json|pnpm-lock.yaml|yarn.lock|bun.lockb|Cargo.lock|poetry.lock|composer.lock)
    REASON="lockfile (regenerate via the package manager, do not hand-edit)" ;;
esac

# Anything inside a .git/ directory.
[[ "$FILE" =~ (^|/)\.git/ ]] && REASON="internal git metadata"

if [[ -n "${REASON:-}" ]]; then
  printf "protect-sensitive-files: refusing to edit %s\n" "$FILE" >&2
  printf "Reason: %s.\n" "$REASON" >&2
  printf "If this is a deliberate, reviewed edit: VOID_HARNESS_ALLOW_SECRET_EDIT=1.\n" >&2
  exit 2
fi

exit 0
