// Compile the Codex-side safety floor into a consumer project. Claude Code gets
// its floor auto-wired through .claude/settings.json (the marketplace plugin's
// PreToolUse hooks); Codex's equivalent is a project-local .codex/hooks.json
// pointing at resolvable hook scripts. `init` stages the scripts under
// .void/hooks/ and writes .codex/hooks.json compiled from the shipped template
// (packages/core/codex/hooks.json), so the former manual three-step opt-in
// (docs/CODEX.md) is now automatic and symmetric with the Claude path.
//
// This module owns the whole Codex-floor domain: the pure transforms
// (compile/reference/drift), the imperative staging (wire), and the two
// decision functions the adapter/commands read (health for doctor, refresh for
// update). Keeping them here means init/doctor/update never re-implement floor
// logic — they format results this module returns.

import { cp, mkdir, readFile, rename, stat, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

async function readOrUndefined(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8');
  } catch {
    return undefined;
  }
}

async function isExecutable(path: string): Promise<boolean> {
  try {
    return ((await stat(path)).mode & 0o111) !== 0;
  } catch {
    return false;
  }
}

// The floor is a fixed, enumerable set: the two guardrail hooks plus the two
// libraries they source relative to their own location (`${BASH_SOURCE[0]%/*}`).
// Kept explicit rather than globbed because this is a security surface — growing
// it must be a deliberate act, and the drift-guard test below asserts this set
// still covers every command the template references.
export const CODEX_FLOOR_SCRIPTS = [
  'block-dangerous-bash.sh',
  'protect-sensitive-files.sh',
  '_hooklib.sh',
  '_checks.sh',
] as const;

// Project-relative directory the scripts are staged into, and the value we
// substitute for the template's ${VOID_HOOKS_DIR} placeholder. Relative (not an
// absolute machine path) so .codex/hooks.json stays committable and portable
// across a team; mirrors the runtime running hooks with cwd at the project root.
export const CODEX_HOOKS_DIR = '.void/hooks';

// biome-ignore lint/suspicious/noTemplateCurlyInString: this IS the literal placeholder token, matched verbatim.
const PLACEHOLDER = '${VOID_HOOKS_DIR}';

function substituteHooksDir(template: string, hooksDir: string): string {
  return template.split(PLACEHOLDER).join(hooksDir);
}

/**
 * Compile the shipped Codex hooks template into the manifest written to
 * <project>/.codex/hooks.json: substitute every ${VOID_HOOKS_DIR} with the
 * staged hooks dir, and rewrite the `$comment` — the template's is a manual
 * install guide that no longer applies once `init` automates the wiring.
 * Throws on a template that isn't a JSON object (a corrupt shipped asset must
 * fail loudly at wire time, never write a garbage manifest).
 */
export function compileCodexHooksManifest(template: string, hooksDir: string = CODEX_HOOKS_DIR): string {
  const parsed: unknown = JSON.parse(substituteHooksDir(template, hooksDir));
  if (parsed === null || typeof parsed !== 'object' || Array.isArray(parsed)) {
    throw new Error('codex hooks template is not a JSON object');
  }
  const manifest: Record<string, unknown> = { ...parsed };
  manifest.$comment =
    `Generated by \`void-harness init\` — the Codex-side safety floor, mirror of the Claude Code ` +
    `PreToolUse hooks. Scripts are staged in ${hooksDir}/; re-run \`void-harness init\` to refresh. ` +
    `See docs/CODEX.md.`;
  return JSON.stringify(manifest, null, 2);
}

/**
 * Every script basename the manifest invokes under `hooksDir`. Accepts either
 * the raw template (with the ${VOID_HOOKS_DIR} placeholder) or an
 * already-compiled/on-disk manifest. Pure string scan — never parses/mutates,
 * so a malformed (scalar/null) manifest yields `[]` rather than throwing. Drift
 * guard: the result must be a subset of CODEX_FLOOR_SCRIPTS, else a hook would
 * be wired-but-absent after `init` copies only the known scripts.
 */
export function referencedScripts(manifest: string, hooksDir: string = CODEX_HOOKS_DIR): string[] {
  const substituted = substituteHooksDir(manifest, hooksDir);
  const prefix = `${hooksDir}/`;
  const found = new Set<string>();
  for (const match of substituted.matchAll(/"command"\s*:\s*"([^"]+)"/g)) {
    const cmd = match[1] ?? '';
    if (cmd.startsWith(prefix)) found.add(cmd.slice(prefix.length));
  }
  return [...found];
}

/**
 * Stage the Codex safety floor into a consumer project (imperative shell): copy
 * the floor scripts into <project>/.void/hooks/ and compile
 * <project>/.codex/hooks.json from the shipped template. Shared by `init` (first
 * wire) and `update` (refresh to the running CLI's version), so the two can
 * never drift in how the floor is materialized. Idempotent: re-running
 * overwrites the managed scripts + manifest in place. `sourceRoot` is the
 * located `packages/core` tree (findCoreSource). Returns how many scripts were
 * staged so the caller can phrase the status line itself.
 *
 * The manifest is written via a temp-file rename so a reader never observes a
 * half-written .codex/hooks.json.
 */
export async function wireCodexFloor(projectRoot: string, sourceRoot: string): Promise<number> {
  const hooksSrc = join(sourceRoot, 'hooks');
  const hooksDst = join(projectRoot, CODEX_HOOKS_DIR);
  await mkdir(hooksDst, { recursive: true });
  for (const script of CODEX_FLOOR_SCRIPTS) {
    // cp copies the mode by default, preserving the executable bit the two
    // entry-point hooks need to run as a command.
    await cp(join(hooksSrc, script), join(hooksDst, script));
  }

  const template = await readFile(join(sourceRoot, 'codex', 'hooks.json'), 'utf8');
  const manifest = compileCodexHooksManifest(template);
  const codexDir = join(projectRoot, '.codex');
  await mkdir(codexDir, { recursive: true });
  const manifestPath = join(codexDir, 'hooks.json');
  const tmpPath = `${manifestPath}.tmp`;
  await writeFile(tmpPath, manifest.endsWith('\n') ? manifest : `${manifest}\n`);
  await rename(tmpPath, manifestPath);

  return CODEX_FLOOR_SCRIPTS.length;
}

/**
 * Which floor files staged in the project differ from what the running CLI would
 * write (`sourceRoot` = findCoreSource). Empty ⇒ the staged floor is already at
 * the CLI's version. Lets `update` refresh only on real drift and report
 * fresh/refreshed honestly instead of rewriting identical files every run.
 * Trailing-newline differences are ignored (wireCodexFloor appends one).
 */
export async function codexFloorDrift(projectRoot: string, sourceRoot: string): Promise<string[]> {
  const drift: string[] = [];
  const hooksSrc = join(sourceRoot, 'hooks');
  const hooksDst = join(projectRoot, CODEX_HOOKS_DIR);
  for (const script of CODEX_FLOOR_SCRIPTS) {
    const [src, dst] = await Promise.all([
      readOrUndefined(join(hooksSrc, script)),
      readOrUndefined(join(hooksDst, script)),
    ]);
    if (src !== dst) drift.push(script);
  }

  const template = await readOrUndefined(join(sourceRoot, 'codex', 'hooks.json'));
  const expected = template === undefined ? undefined : compileCodexHooksManifest(template);
  const actual = await readOrUndefined(join(projectRoot, '.codex', 'hooks.json'));
  const trimEnd = (s: string | undefined): string => (s ?? '').replace(/\n+$/, '');
  if (trimEnd(actual) !== trimEnd(expected)) drift.push('hooks.json');
  return drift;
}

export interface CodexFloorHealth {
  readonly ok: boolean;
  readonly detail: string;
}

/**
 * Health of the staged Codex floor, for `doctor`. Never throws (all fs +
 * parse failures map to an `ok: false` detail), so a corrupt manifest reports a
 * red line instead of crashing the whole health check. Verifies the floor is
 * actually live, not merely present:
 *   - manifest exists, is valid JSON, and is an object;
 *   - it references at least one staged command;
 *   - EVERY floor script is staged (entry hooks AND the libs they source — a
 *     missing _hooklib.sh makes the hooks fail at runtime);
 *   - the referenced entry hooks are executable.
 */
export async function codexFloorHealth(projectRoot: string): Promise<CodexFloorHealth> {
  const manifest = await readOrUndefined(join(projectRoot, '.codex', 'hooks.json'));
  if (manifest === undefined) return { ok: false, detail: '.codex/ present but hooks.json missing' };

  let parsed: unknown;
  try {
    parsed = JSON.parse(manifest);
  } catch {
    return { ok: false, detail: '.codex/hooks.json is not valid JSON' };
  }
  if (parsed === null || typeof parsed !== 'object') {
    return { ok: false, detail: '.codex/hooks.json is not a JSON object' };
  }

  const entryHooks = referencedScripts(manifest);
  if (entryHooks.length === 0) return { ok: false, detail: '.codex/hooks.json references no staged scripts' };

  const hooksDir = join(projectRoot, CODEX_HOOKS_DIR);
  const missing: string[] = [];
  for (const script of CODEX_FLOOR_SCRIPTS) {
    if ((await readOrUndefined(join(hooksDir, script))) === undefined) missing.push(script);
  }
  if (missing.length > 0) return { ok: false, detail: `staged scripts missing: ${missing.join(', ')}` };

  const notExecutable: string[] = [];
  for (const hook of entryHooks) {
    if (!(await isExecutable(join(hooksDir, hook)))) notExecutable.push(hook);
  }
  if (notExecutable.length > 0) {
    return { ok: false, detail: `staged hooks not executable: ${notExecutable.join(', ')}` };
  }

  return {
    ok: true,
    detail: `wired: ${CODEX_FLOOR_SCRIPTS.length} scripts staged in ${CODEX_HOOKS_DIR}/ (${entryHooks.length} executable hook(s))`,
  };
}

export type CodexFloorRefresh =
  | { readonly status: 'fresh'; readonly drift: readonly string[] }
  | { readonly status: 'would-refresh'; readonly drift: readonly string[] }
  | { readonly status: 'refreshed'; readonly drift: readonly string[] };

/**
 * Bring the staged floor to the running CLI's version, for `update`. Re-stages
 * only on real content drift so a no-op update stays a no-op; the status is
 * honest about whether files were actually written (`refreshed`) versus a
 * dry-run preview (`would-refresh`). Assumes the caller already established that
 * Codex is wired and located `sourceRoot`.
 */
export async function refreshCodexFloor(
  projectRoot: string,
  sourceRoot: string,
  dryRun: boolean,
): Promise<CodexFloorRefresh> {
  const drift = await codexFloorDrift(projectRoot, sourceRoot);
  if (drift.length === 0) return { status: 'fresh', drift };
  if (dryRun) return { status: 'would-refresh', drift };
  await wireCodexFloor(projectRoot, sourceRoot);
  return { status: 'refreshed', drift };
}
