// Who owns each path the harness materializes, and therefore what git does with it.
//
// The problem this solves is not cosmetic. `.void/` held two things with
// opposite lifecycles — what the project DECLARES (config.json,
// PROJECT-DOCTRINE.md: authored, reviewed, pushed) and what the harness OBSERVES
// (telemetry, run journals, caches: machine-local, never shipped) — and nothing
// separated them, so every project improvised its own ignore rule over a vacuum.
// The one that prompted this read:
//
//     .void/*
//     !.void/PROJECT-DOCTRINE.md
//
// It rescued the doctrine and silently ignored `config.json` with it — the file
// carrying the pack pins and `paths.business`, the glob the enforcement runner
// reads to decide what the TDD guard covers. A teammate cloning that repo got the
// doctrine and no enforcement configuration, with nothing reporting it.
//
// The fix is a classification, not a longer exception list:
//
//   project   the project authors it, the harness never overwrites it, it ships
//   derived   re-materialized by `init` from the harness assets
//   observed  machine-local history, meaningless in another checkout
//
// Observed state moves under `.void/local/`, so its ignore rule is one line with
// no `!` and — the property that actually matters — stops needing maintenance: a
// new runtime artifact is born inside `local/` and no ignore file learns about it.
//
// `derived` is ignored too, EXCEPT what a fresh clone needs to work: the runner
// `.claude/settings.json` names, and the Codex safety floor. And it is ignored
// PER RECEIPT, never per directory — `.claude/skills/` also holds skills the
// project wrote by hand, and inferring ownership from the folder would ignore
// them and let `--untrack-derived` drop them from the index.
//
// Pure except for the three functions documented as touching the filesystem.

import { existsSync } from 'node:fs';
import { join } from 'node:path';

export const VOID_DIR = '.void';
export const VOID_LOCAL_DIR = 'local';

/** What a materialized path is, which is what decides whether git keeps it. */
export type Ownership = 'project' | 'derived' | 'observed';

/**
 * Ownership of every direct child of `.void/`, and the single source of truth the
 * ignore rule, the migration and `doctor` all read. A second copy of this
 * anywhere would let `update` move a file the ignore rule does not cover, and the
 * next commit would ship telemetry.
 */
export const VOID_OWNERSHIP: Readonly<Record<string, Ownership>> = Object.freeze({
  // Declared: authored or hand-edited, never regenerable from a pin.
  'config.json': 'project',
  'PROJECT-DOCTRINE.md': 'project',
  'pricing.json': 'project',
  policies: 'project',
  profiles: 'project',
  organization: 'project',

  // Derived: `void-harness init` re-materializes these from the harness assets.
  // NOT an exact restore — see the reproducibility limit in the ADR.
  'PHILOSOPHY.md': 'derived',
  hooks: 'derived',

  // Observed: this machine's history. Never meaningful in another checkout.
  runs: 'observed',
  cache: 'observed',
  outputs: 'observed',
  generated: 'observed',
  archives: 'observed',
  autopilot: 'observed',
  receipts: 'observed',
  history: 'observed',
  worktrees: 'observed',
  'autonomous-runs': 'observed',
  'state.json': 'observed',
  'activations.jsonl': 'observed',
  'outcomes.jsonl': 'observed',
  'usage.log': 'observed',
  '.registered': 'observed',
});

/**
 * The paths the harness materializes OUTSIDE `.void/`, with their class. Same
 * axis, wider scope: `.claude/`, `.agents/` and `.codex/` hold the same mix of
 * project state and regenerated content, and left unclassified they were tracked
 * by default — 126 files and ~1.2 MB of vendored prose per consumer repository,
 * rewritten in full on every version bump, in every review diff.
 *
 * A trailing slash marks a directory prefix.
 */
export const MATERIALIZED_OWNERSHIP: Readonly<Record<string, Ownership>> = Object.freeze({
  // The project's own wiring: hand-editable, merged rather than regenerated.
  '.claude/settings.json': 'project',

  // Regenerated by `init` from the harness assets.
  '.claude/skills/': 'derived',
  '.claude/agents/': 'derived',
  '.claude/commands/': 'derived',
  '.agents/skills/': 'derived',
  '.codex/agents/': 'derived',
  '.void/hooks/': 'derived',
  '.void/PHILOSOPHY.md': 'derived',
  '.codex/hooks.json': 'derived',
});

/**
 * Derived paths that stay TRACKED regardless, because their absence is an error
 * rather than a degradation:
 *
 * - `.void/hooks/` is referenced by name from `.claude/settings.json`, which is
 *   project state and therefore committed. Ignoring the runner while keeping the
 *   reference gives a fresh clone a settings file pointing at a missing file, and
 *   every tool call fails on it.
 * - `.codex/hooks.json` IS the Codex safety floor. Absent, the floor is simply
 *   not there — a silently weaker clone, which is the worst of the three states.
 *
 * Everything else in the derived class degrades gracefully: without them the
 * agent has fewer capabilities until the next `init`, and nothing errors.
 */
export const DERIVED_LOAD_BEARING: readonly string[] = Object.freeze([
  '.void/hooks/',
  '.codex/hooks.json',
]);

/**
 * Roots whose direct children are self-contained units — one skill, one agent,
 * one command. Used only to keep the generated ignore block readable: a unit the
 * receipt owns collapses to `<root>/<unit>/` instead of listing its every file.
 */
const UNIT_ROOTS: readonly string[] = Object.freeze([
  '.claude/skills',
  '.claude/agents',
  '.claude/commands',
  '.agents/skills',
  '.codex/agents',
]);

function normalize(path: string): string {
  return path.split('\\').join('/');
}

/**
 * Classify a materialized path by prefix.
 *
 * **Only ever apply this to paths the install receipt claims.** These directories
 * are SHARED with the project — `.claude/skills/` is where Claude Code reads a
 * project's own skills, and the harness merely also writes there. Classifying by
 * directory alone would call a hand-written `.claude/skills/custom/` "derived",
 * silently ignore it, and let `--untrack-derived` drop it from the index. The
 * receipt is the ownership truth; this only says what KIND of harness file it is.
 */
export function classifyMaterialized(path: string): Ownership | undefined {
  const target = normalize(path);
  for (const [prefix, ownership] of Object.entries(MATERIALIZED_OWNERSHIP)) {
    if (prefix.endsWith('/') ? target.startsWith(prefix) : target === prefix) return ownership;
  }
  return undefined;
}

/** True when this receipt-owned path is derived AND safe to leave out of a clone. */
export function isOwnedDerived(path: string): boolean {
  const target = normalize(path);
  if (classifyMaterialized(target) !== 'derived') return false;
  return !DERIVED_LOAD_BEARING.some((kept) =>
    kept.endsWith('/') ? target.startsWith(kept) : target === kept,
  );
}

/**
 * The ignore entries for the derived files the RECEIPT says the harness owns —
 * never a whole runtime directory. A unit the receipt owns collapses to its
 * directory so the block stays readable; anything else is listed exactly.
 *
 * A path the receipt does not claim can never appear here, which is the entire
 * safety property: the project's own skills and agents stay visible to git.
 */
export function derivedIgnoreEntries(ownedPaths: readonly string[]): string[] {
  const entries = new Set<string>();
  for (const raw of ownedPaths) {
    const path = normalize(raw);
    if (!isOwnedDerived(path)) continue;
    const root = UNIT_ROOTS.find((candidate) => path.startsWith(`${candidate}/`));
    if (root === undefined) {
      entries.add(path);
      continue;
    }
    // Collapse only when the unit is a DIRECTORY, i.e. there is another segment
    // below it. `.claude/agents/` holds files directly, and emitting
    // `.claude/agents/doctrine-critic.md/` with a trailing slash matches a
    // directory that does not exist — so git ignored none of them.
    const rest = path.slice(root.length + 1).split('/');
    const unit = rest[0] ?? '';
    entries.add(unit === '' || rest.length < 2 ? path : `${root}/${unit}/`);
  }
  return [...entries].sort();
}

/** The observed entries, sorted — what moves under `local/` and what git ignores. */
export const LOCAL_ENTRIES: readonly string[] = Object.freeze(
  Object.keys(VOID_OWNERSHIP)
    .filter((entry) => VOID_OWNERSHIP[entry] === 'observed')
    .sort(),
);

const BEGIN_MARKER = '# void-harness:begin';
const END_MARKER = '# void-harness:end';

/**
 * Ownership of a direct child of `.void/`. An entry this version has never heard
 * of answers `project`, and that is the safe answer rather than the lax one:
 * `local/` is a CLOSED set — every observed writer in the harness now writes
 * inside it — so a stranger at the top of `.void/` cannot be our telemetry. It is
 * someone's file, and the failure of guessing wrong is "doctor tells a project to
 * untrack its own data", which is worse than tracking one unknown path.
 *
 * The legacy names left over from before the split are enumerated above, so they
 * are recognised as observed rather than falling through to this default.
 */
export function ownershipOf(entry: string): Ownership {
  return VOID_OWNERSHIP[entry] ?? 'project';
}

/** True when this direct child of `.void/` is observed state rather than declared. */
export function isLocalEntry(entry: string): boolean {
  return ownershipOf(entry) === 'observed';
}

/** `<root>/.void` — holds the declared half, tracked by git in full. */
export function voidDir(root: string): string {
  return join(root, VOID_DIR);
}

/** `<root>/.void/local` — the observed half, covered by one ignore rule. */
export function voidLocalDir(root: string): string {
  return join(root, VOID_DIR, VOID_LOCAL_DIR);
}

/** Path to an observed artifact at its post-split location. Writers use this. */
export function voidLocalPath(root: string, ...segments: readonly string[]): string {
  return join(voidLocalDir(root), ...segments);
}

/** Path to an artifact at its pre-split location. Readers use this only as a fallback. */
export function legacyVoidPath(root: string, ...segments: readonly string[]): string {
  return join(voidDir(root), ...segments);
}

/**
 * Where to READ an observed artifact: the migrated path when it exists, the
 * pre-split one while it still holds the data, and the migrated path when neither
 * does (so a writer handed this creates the right one).
 *
 * Touches the filesystem. The fallback is what stops a project that has not run
 * `update` yet from reporting months of telemetry as none.
 */
export function voidLocalReadPath(root: string, ...segments: readonly string[]): string {
  const migrated = voidLocalPath(root, ...segments);
  if (existsSync(migrated)) return migrated;
  const legacy = legacyVoidPath(root, ...segments);
  return existsSync(legacy) ? legacy : migrated;
}

/**
 * The observed artifacts still sitting at the pre-split location, for `update` to
 * move. Sorted, and empty for a project already migrated or never installed.
 *
 * Touches the filesystem.
 */
export function pendingMigrations(root: string): string[] {
  return LOCAL_ENTRIES.filter((entry) => existsSync(legacyVoidPath(root, entry))).sort();
}

/**
 * The managed `.gitignore` block. `derivedEntries` comes from
 * `derivedIgnoreEntries(receipt.files)` — pass an empty list and the block covers
 * observed state only, which is what a project with no readable receipt gets.
 */
export function gitignoreBlock(derivedEntries: readonly string[] = []): string {
  if (derivedEntries.length === 0) {
    return [
      BEGIN_MARKER,
      '# Everything the harness OBSERVES (telemetry, run journals, caches, install',
      '# receipts) lives under .void/local/ and is machine-local. Everything the',
      '# project DECLARES (config.json, PROJECT-DOCTRINE.md, policies/) stays tracked',
      '# at the top of .void/ — config.json in particular carries the pack pins and',
      '# paths.business, which the enforcement runner needs on a fresh clone.',
      '# No exception rule: a new runtime artifact is born inside local/ and this',
      '# file never has to learn about it.',
      `${VOID_DIR}/${VOID_LOCAL_DIR}/`,
      END_MARKER,
    ].join('\n');
  }
  return [
    BEGIN_MARKER,
    '# Everything the harness OBSERVES (telemetry, run journals, caches, install',
    '# receipts) lives under .void/local/ and is machine-local. Everything the',
    '# project DECLARES (config.json, PROJECT-DOCTRINE.md, policies/) stays tracked',
    '# at the top of .void/ — config.json in particular carries the pack pins and',
    '# paths.business, which the enforcement runner needs on a fresh clone.',
    '# No exception rule: a new runtime artifact is born inside local/ and this',
    '# file never has to learn about it.',
    `${VOID_DIR}/${VOID_LOCAL_DIR}/`,
    '',
    '# Regenerated by `void-harness init` from the harness assets. Listed one by',
    '# one from the install receipt — NEVER a whole runtime directory, because',
    '# .claude/skills/ and its siblings are shared: a skill this project wrote by',
    '# hand lives there too, and it must stay visible to git.',
    '# Absent, the agent has fewer capabilities until the next init — it degrades,',
    '# it does not break. Deliberately still tracked: .void/hooks/ (named from the',
    '# tracked .claude/settings.json) and .codex/hooks.json (the safety floor) —',
    '# their absence is an error, not a degradation.',
    ...derivedEntries,
    END_MARKER,
  ].join('\n');
}

/**
 * Add or refresh the managed block in a `.gitignore`, leaving every rule the
 * project wrote itself untouched. Idempotent: patching an already-patched file
 * with the same entries returns it unchanged.
 */
export function patchGitignore(original: string, derivedEntries: readonly string[] = []): string {
  const block = gitignoreBlock(derivedEntries);
  const begin = original.indexOf(BEGIN_MARKER);
  const end = original.indexOf(END_MARKER);
  if (begin !== -1 && end !== -1) {
    const replaced = `${original.slice(0, begin)}${block}${original.slice(end + END_MARKER.length)}`;
    return replaced.endsWith('\n') ? replaced : `${replaced}\n`;
  }
  const base = original === '' || original.endsWith('\n') ? original : `${original}\n`;
  return `${base}${base === '' ? '' : '\n'}${block}\n`;
}
