/**
 * The README states how much harness there is. This proves the numbers, and it
 * proves them against the graph model rather than by counting files again.
 *
 * The first version of this test walked the directories itself and reported 31
 * hooks while `model.json` reported 33 — two answers to one question, which is
 * the failure the whole graph exists to prevent. A count is only trustworthy if
 * it comes from the catalogue every other surface already reads.
 *
 * The model is regenerated by `void-harness graph build`, which `pnpm verify`
 * gates. Adding a skill therefore fails this test until both the model and the
 * README are updated, in the same commit.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const ROOT = resolve(__dirname, '..', '..');
const README = readFileSync(resolve(ROOT, 'README.md'), 'utf8');

interface ModelNode {
  readonly id?: string;
  readonly type?: string;
  readonly kind?: string;
  readonly pack?: string | null;
}

const model = JSON.parse(readFileSync(resolve(ROOT, 'packages/core/data/model.json'), 'utf8')) as {
  nodes?: readonly ModelNode[];
};
const nodes: readonly ModelNode[] = model.nodes ?? [];

function ofType(type: string): readonly ModelNode[] {
  return nodes.filter((node) => (node.type ?? node.kind) === type);
}

/** The number the README states for a row of the composition table. */
function statedCount(label: string): number {
  const row = new RegExp(`\\|\\s*${label}\\s*\\|\\s*(\\d+)\\s*\\|`).exec(README);
  if (row === null) throw new Error(`README has no composition row for "${label}"`);
  return Number(row[1]);
}

describe('the README composition table matches the graph model', () => {
  it('reads a model that actually carries nodes, so an empty file cannot pass everything', () => {
    expect(nodes.length).toBeGreaterThan(50);
  });

  it('counts core skills', () => {
    const core = ofType('skill').filter((skill) => skill.pack == null);
    expect(statedCount('Core skills')).toBe(core.length);
  });

  it('counts stack pack skills', () => {
    const packed = ofType('skill').filter((skill) => skill.pack != null);
    expect(statedCount('Stack pack skills')).toBe(packed.length);
  });

  it('counts hooks', () => {
    expect(statedCount('Hooks')).toBe(ofType('hook').length);
  });

  it('counts agents', () => {
    expect(statedCount('Agents')).toBe(ofType('agent').length);
  });

  it('counts specialists', () => {
    // Specialists are contracts rather than graph nodes, so they are counted at
    // their source. If they ever enter the model, read them from it instead.
    const actual = readdirSync(resolve(ROOT, 'packages/core/specialists')).filter((name) =>
      name.endsWith('.yaml'),
    ).length;
    expect(statedCount('Specialists')).toBe(actual);
  });
});

describe('the commands the README advertises', () => {
  const help = readFileSync(resolve(ROOT, 'packages/cli/src/commands/help.ts'), 'utf8');

  it.each([['status'], ['doctor'], ['add'], ['runtime'], ['update'], ['init']])(
    '`%s` exists in the CLI help',
    (command) => {
      expect(README).toContain(`voidharness ${command}`);
      expect(help).toContain(command);
    },
  );

  it('states no version number, because a release ages one out silently', () => {
    // The npm badge reads the live version; nothing else should hardcode it.
    const body = README.split('\n').filter((line) => !line.includes('img.shields.io'));
    expect(body.join('\n')).not.toMatch(/\b\d+\.\d+\.\d+\b/);
  });
});
