/**
 * The product identity has one source, packages/core/data/identity.json. Code reads it; the
 * files that cannot import it (npm manifests, plugin manifests, workflows) repeat it, and this
 * contract is what keeps the repetitions honest, in the spirit of `version:check`.
 *
 * It also retires the names the product carried before: an old slug or an old package name left
 * anywhere outside the historical record would point a reader, a guard or an installer at a
 * repository or a package that is no longer ours.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { PRODUCT_IDENTITY } from '../../packages/hook-runner/src/identity.js';
// @ts-expect-error -- plain ESM script, no types
import { PRODUCT_IDENTITY as SCRIPT_IDENTITY } from '../../scripts/product-identity.mjs';

const ROOT = resolve(import.meta.dirname, '../..');
const { repositorySlug, repositoryUrl, packageName, commands, repository } = PRODUCT_IDENTITY;

/**
 * Names the product no longer answers to. The identity keeps them, because it has to know where an
 * old release lives and which workflow references a rename broke; nothing else may.
 */
const RETIRED_NAMES = [
  ...PRODUCT_IDENTITY.formerRepositorySlugs,
  ...PRODUCT_IDENTITY.formerPackages.map((former) => former.name),
];
const SOURCE = 'packages/core/data/identity.json';

/** The historical record keeps the names it was written with; the rest of the tree may not. */
const HISTORICAL = [
  /^docs\/(decisions-log|plans|specs|audits)\//,
  /^docs\/DECISIONS\.md$/,
  // A migration guide to a released version names the package that version shipped under.
  /^docs\/MIGRATING-[\d.]+\.md$/,
  /(^|\/)CHANGELOG\.md$/,
  /^\.void\/requests\.md$/,
];

/** Released or generated bytes: they change when they are rebuilt, never by hand. */
const GENERATED = [
  /^\.void\/hooks\//,
  /^\.void\/knowledge\.json$/,
  /^packages\/cli\/core-assets\//,
  /^packages\/core\/hooks\/_void-hook\.mjs$/,
  /^packages\/core\/hooks\/_syntax-worker\.cjs$/,
  /^packages\/core\/graph\/void-graph\.mjs$/,
];

const SELF = 'test/identity/product-identity.test.ts';
const CODE = /\.(?:[cm]?[jt]s|tsx|sh)$|^\.githooks\//;
const BINARY = /\.(?:png|jpe?g|gif|ico|webp|woff2?|pdf)$/;

function trackedFiles(): string[] {
  return execFileSync('git', ['ls-files', '-z'], { cwd: ROOT, encoding: 'utf8' })
    .split('\0')
    .filter((path) => path !== '' && !BINARY.test(path));
}

function read(path: string): string {
  return readFileSync(resolve(ROOT, path), 'utf8');
}

function readJson(path: string): Record<string, unknown> {
  return JSON.parse(read(path)) as Record<string, unknown>;
}

function holders(paths: readonly string[], needle: string): string[] {
  return paths.filter((path) => read(path).includes(needle));
}

const exempt = (path: string, rules: readonly RegExp[]) => rules.some((rule) => rule.test(path));

describe('the identity source', () => {
  it('reads the same values from TypeScript and from the plain-ESM scripts', () => {
    expect(JSON.parse(JSON.stringify(SCRIPT_IDENTITY))).toEqual(JSON.parse(JSON.stringify(PRODUCT_IDENTITY)));
  });
});

describe('manifests that cannot import the identity', () => {
  it('point every workspace link at the repository', () => {
    const manifest = readJson('package.json');
    expect(manifest['homepage']).toBe(repositoryUrl);
    expect(manifest['repository']).toEqual({ type: 'git', url: `git+${repositoryUrl}.git` });
    expect(manifest['bugs']).toEqual({ url: `${repositoryUrl}/issues` });
  });

  it('publish the CLI under the package name, from this repository', () => {
    const manifest = readJson('packages/cli/package.json');
    expect(manifest['name']).toBe(packageName);
    expect(manifest['homepage']).toBe(`${repositoryUrl}#readme`);
    expect(manifest['repository']).toEqual({
      type: 'git',
      url: `git+${repositoryUrl}.git`,
      directory: 'packages/cli',
    });
    expect(manifest['bugs']).toEqual({ url: `${repositoryUrl}/issues` });
  });

  it('install every declared command and no other, the deprecated ones through their own entry', () => {
    const bin = readJson('packages/cli/package.json')['bin'];
    const expected = Object.fromEntries([
      ...[commands.primary, ...commands.aliases].map((name) => [name, `./bin/${commands.primary}.mjs`]),
      ...commands.deprecated.map((name) => [name, `./bin/${name}.mjs`]),
    ]);
    expect(bin).toEqual(expected);
  });

  it('link every plugin manifest to the repository', () => {
    const manifests = trackedFiles().filter((path) => path.endsWith('.claude-plugin/plugin.json'));
    expect(manifests.length).toBeGreaterThan(0);
    for (const path of manifests) expect([path, readJson(path)['homepage']]).toEqual([path, repositoryUrl]);
  });
});

describe('workflows, which compare against a literal of their own', () => {
  const workflows = trackedFiles().filter((path) => path.startsWith('.github/workflows/'));

  it('pin every repository guard to the identity slug', () => {
    const guards = workflows.flatMap((path) =>
      [...read(path).matchAll(/^\s*EXPECTED_REPOSITORY:\s*(\S+)\s*$/gm)].map((match) => [path, match[1]]),
    );
    expect(guards.length).toBeGreaterThanOrEqual(5);
    for (const [path, value] of guards) expect([path, value]).toEqual([path, repositorySlug]);
  });

  it('pin the owner and name guards to the identity', () => {
    const promotion = read('.github/workflows/promotion.yml');
    expect(promotion).toMatch(new RegExp(`^\\s*EXPECTED_OWNER: ${repository.owner}$`, 'm'));
    expect(promotion).toMatch(new RegExp(`^\\s*EXPECTED_NAME: ${repository.name}$`, 'm'));
  });

  it('name no repository of the owner other than this one', () => {
    const pattern = new RegExp(`${repository.owner}/([A-Za-z0-9._-]+)`, 'g');
    for (const path of workflows) {
      const others = [...read(path).matchAll(pattern)].map((match) => match[1]).filter((name) => name !== repository.name);
      expect([path, others]).toEqual([path, []]);
    }
  });

  it('spell the package name only in the EXPECTED_PACKAGE variable every step reads', () => {
    for (const path of workflows) {
      const stray = read(path)
        .split('\n')
        .filter((line) => line.includes(packageName) && !/^\s*EXPECTED_PACKAGE:/.test(line));
      expect([path, stray]).toEqual([path, []]);
    }
    const release = read('.github/workflows/release.yml');
    expect(release).toMatch(new RegExp(`^\\s*EXPECTED_PACKAGE: ${packageName}$`, 'm'));
  });
});

describe('literals outside the identity source', () => {
  const files = trackedFiles();

  it('code never spells the repository slug or the package name', () => {
    const code = files.filter((path) => CODE.test(path) && path !== SELF && !exempt(path, GENERATED));
    expect(holders(code, repositorySlug)).toEqual([]);
    expect(code.filter((path) => new RegExp(`(?<![\\w@/-])${packageName}(?![\\w-])`).test(read(path)))).toEqual([]);
  });

  it('knows at least one retired name, or this guard would pass on an empty list', () => {
    expect(RETIRED_NAMES.length).toBeGreaterThan(0);
  });

  it.each(RETIRED_NAMES)('%s survives only in the historical record', (retired) => {
    const live = files.filter((path) => path !== SELF && path !== SOURCE && !exempt(path, [...HISTORICAL, ...GENERATED]));
    expect(holders(live, retired)).toEqual([]);
  });
});
